spring.application.name=local_to_smartapi

broker.api.base-url=https://apiconnect.angelone.in
broker.api.timeout.connect=2000
broker.api.timeout.response=2000


angel.base-url=https://apiconnect.angelone.in
angel.private-key=5hva6iDv
angel.client-local-ip=192.168.1.10
angel.client-public-ip=123.145.22.11
angel.client-mac-address=AA-BB-CC-DD-EE-FF
angel.source-id=WEB
angel.user-type=USER
angel.totp-code=PF3ZHJPRNE7GDEVMRUIXQ6CFGE

myapp.token.file-path=D:/1 percent growth trading/tokens.json
myapp.scripmaster.file-path=D:/1 percent growth trading/scripmaster.json
myapp.sl_orderstore.file-path=D:/1 percent growth trading/

# Requests are rejected if available balance is <= this value
myapp.balance-minimum-allowed=0

# Order is rejected if max purchasable quantity is <= this value
myapp.stock-buy-minimum-quantity-required=0

#0.98 = (1 + 0.5)%
myapp.profit-percentage-multiplier=1.05

#0.98 = (1 - 0.2)%
myapp.stoploss-percentage-multiplier=0.98

#1000 milis = 1 sec
myapp.order-book-retry-milliseconds=1000

#1 = 100%, 0.5 = 50% balance use
myapp.percent-balance-use=1

#after calculating the quantity for safety reduce this much quantity from final quantity
myapp.number-of-stocks-buy-less=1


