spring.application.name=local_to_smartapi

info.app.name=${spring.application.name}
info.app.version=@project.version@

broker.api.base-url=https://apiconnect.angelone.in
broker.api.timeout.connect=2000
broker.api.timeout.response=2000


angel.base-url=https://apiconnect.angelone.in
angel.client-local-ip=192.168.1.10
angel.client-public-ip=123.145.22.11
angel.client-mac-address=AA-BB-CC-DD-EE-FF
angel.source-id=WEB
angel.user-type=USER
angel.client-id=${ANGEL_CLIENT_ID}
angel.password=${ANGEL_PASSWORD}
angel.totp-code=${ANGEL_TOTP}
angel.private-key=${ANGEL_PRIVATE_KEY}

#myPC windows path
myapp.token-file-path=D:/1 percent growth trading/tokens.json
myapp.scripmaster-file-path=D:/1 percent growth trading/scripmaster.json
myapp.filtered-scripmaster-file-path=D:/1 percent growth trading/scrip_master_nse_eq.json
myapp.rms-balance-file-path=D:/1 percent growth trading/rmsbalance.json
myapp.scripmaster-fno-list-file-path=D:/1 percent growth trading/fno_stock_list.json
myapp.leverage-list-file-path=D:/1 percent growth trading/leverage_list.json
myapp.sl-orderstore-file-path=D:/1 percent growth trading/

#Raspberry linux config paths
#myapp.token-file-path=/home/trade_conf/tokens.json
#myapp.scripmaster-file-path=/home/trade_conf/scripmaster.json
#myapp.filtered-scripmaster-file-path=/home/trade_conf/scrip_master_nse_eq.json
#myapp.rms-balance-file-path=/home/trade_conf/rmsbalance.json
#myapp.scripmaster-fno-list-file-path=/home/trade_conf/fno_stock_list.json
#myapp.leverage-list-file-path=/home/trade_conf/leverage_list.json
#myapp.sl-orderstore-file-path=/home/trade_conf/

# Requests are rejected if available balance is <= this value
myapp.balance-minimum-allowed=0

# Order is rejected if max purchasable quantity is <= this value
myapp.stock-buy-minimum-quantity-required=0

#0.98 = (1 + 0.5)%
myapp.profit-percentage-multiplier=1.005

#0.98 = (1 - 0.2)%
myapp.stoploss-percentage-multiplier=0.998

#1000 milis = 1 sec
myapp.order-book-retry-milliseconds=1000

#1 = 100%, 0.5 = 50% balance use
myapp.percent-balance-use=1

#after calculating the quantity for safety reduce this much quantity from final quantity
myapp.number-of-stocks-buy-less=0

#this value can be between 1 to 5
myapp.leverage-multiplier-to-use=3

myapp.fixed-quantity-flag=false
myapp.fixed-quantity=2

myapp.trading-window-enable=false
myapp.trading-window-start-time=07:00
myapp.trading-window-end-time=14:30
myapp.trading-window-time-zone=Asia/Kolkata

myapp.rms-auto-refresh-enable=true
myapp.rms-file-overwrite-enabled=true
myapp.rms-refresh-interval-minutes=30

myapp.scripmaster-only-fno-stocks=true
myapp.scripmaster-enable-fno-universe=true

myapp.leverage-enable=true
myapp.leverage-universe=true
myapp.leverage-exchange=NSE