spring.application.name=local_to_smartapi

info.app.name=${spring.application.name}
info.app.version=@project.version@

broker.api.direct-base-url=https://apiconnect.angelone.in
broker.api.proxy-base-url=http://35.209.162.42:9000/proxy
broker.api.timeout.connect=2000
broker.api.timeout.response=2000


angel.base-url=https://apiconnect.angelone.in
angel.client-local-ip=192.168.1.10
angel.client-public-ip=123.145.22.11
angel.client-mac-address=AA-BB-CC-DD-EE-FF
angel.source-id=WEB
angel.user-type=USER
angel.client-id=${ANGEL_CLIENT_ID}
angel.password=${ANGEL_PASSWORD}
angel.totp-code=${ANGEL_TOTP}
angel.private-key=${ANGEL_PRIVATE_KEY}

spring.profiles.active=prod

##myPC windows path
#myapp.token-file-path=D:/1 percent growth trading/tokens.json
#myapp.scripmaster-file-path=D:/1 percent growth trading/scripmaster.json
#myapp.filtered-scripmaster-file-path=D:/1 percent growth trading/scrip_master_nse_eq.json
#myapp.rms-balance-file-path=D:/1 percent growth trading/rmsbalance.json
#myapp.scripmaster-fno-list-file-path=D:/1 percent growth trading/fno_stock_list.json
#myapp.leverage-list-file-path=D:/1 percent growth trading/leverage_list.json
#myapp.sl-orderstore-file-path=D:/1 percent growth trading/
#myapp.order-context-file-path=D:/1 percent growth trading/order-context/
#myapp.excel-to-save-alerts =D:/1 percent growth trading/chartinkAlertExcels/chartinkAllAlerts.xlsx
#myapp.growth-alert-excel-path=D:/1 percent growth trading/chartinkAlertExcels/growth_Alerts.xlsx
#myapp.short-alert-excel-path=D:/1 percent growth trading/chartinkAlertExcels/Short_Alerts.xlsx

#Raspberry linux config paths
myapp.token-file-path=/home/trade_conf/tokens.json
myapp.scripmaster-file-path=/home/trade_conf/scripmaster.json
myapp.filtered-scripmaster-file-path=/home/trade_conf/scrip_master_nse_eq.json
myapp.rms-balance-file-path=/home/trade_conf/rmsbalance.json
myapp.scripmaster-fno-list-file-path=/home/trade_conf/fno_stock_list.json
myapp.leverage-list-file-path=/home/trade_conf/leverage_list.json
myapp.sl-orderstore-file-path=/home/trade_conf/
myapp.order-context-file-path=/home/trade_conf/order-context/
myapp.excel-to-save-alerts =/home/trade_conf/chartinkAlertExcels/chartinkAllAlerts.xlsx
myapp.growth-alert-excel-path=/home/trade_conf/chartinkAlertExcels/growth_Alerts.xlsx
myapp.short-alert-excel-path=/home/trade_conf/chartinkAlertExcels/Short_Alerts.xlsx

## Exchange in which we are trading
#myapp.trading-exchange=NSE

# Requests are rejected if available balance is <= this value
myapp.balance-minimum-allowed=0

# Order is rejected if max purchasable quantity is <= this value
myapp.stock-buy-minimum-quantity-required=0

#1.005 = (1 + 0.05)% = buy price + 0.5%
#value should be greater than 1
myapp.buy-profit-percentage-multiplier=1.005
myapp.default-buy-profit-percentage-multiplier=1.005

#0.98 = (1 - 0.02)% = buy price - 0.2%
#value should be less than 1
myapp.buy-stoploss-percentage-multiplier=0.995
myapp.default-buy-stoploss-percentage-multiplier=0.995


#0.98 = (1 - 0.02)% = buy price - 0.2%
#value should be less than 1
myapp.sell-profit-percentage-multiplier=0.995
myapp.default-sell-profit-percentage-multiplier=0.995

#1.005 = (1 + 0.05)% = buy price + 0.5%
#value should be greater than 1
myapp.sell-stoploss-percentage-multiplier=1.005
myapp.default-sell-stoploss-percentage-multiplier=1.005

#1000 milis = 1 sec
myapp.order-book-retry-milliseconds=1000

#1 = 100%, 0.5 = 50% balance use
myapp.percent-balance-use=1

#after calculating the quantity for safety reduce this much quantity from final quantity
myapp.number-of-stocks-buy-less-for-long=0

#after calculating the quantity for safety reduce this much quantity from final quantity
myapp.number-of-stocks-sell-less-for-short=0

#this value can be between 1 to 5 for long position
myapp.leverage-multiplier-to-use-for-long=1

#this value can be between 1 to 5 for short position
myapp.leverage-multiplier-to-use-for-short=1

myapp.fixed-quantity-flag=true
myapp.fixed-quantity=5


myapp.trading-window-enable=false
myapp.trading-window-start-time=07:00
myapp.trading-window-end-time=14:30
myapp.trading-window-time-zone=Asia/Kolkata

myapp.rms-auto-refresh-enable=true
myapp.rms-file-overwrite-enabled=true
myapp.rms-refresh-interval-minutes=30

myapp.scripmaster-only-fno-stocks=true
myapp.scripmaster-enable-fno-universe=true

myapp.leverage-enable=true
myapp.leverage-universe=true
myapp.leverage-exchange=NSE

#if you keep buffer percent zero then trigger and limit price will be same
#myapp.trading-stoploss-percent=0.004
#myapp.trading-stoploss-buffer-percent=0.001
myapp.trading-stoploss-percent=0.005
myapp.trading-stoploss-buffer-percent=0

myapp.trading-allowDoubleExit=false

#exit strategy properties
myapp.exit-ltp-mode=LTP
myapp.exit-strat-wait-time-after-cancel=300
myapp.squareoff-cron=0 0 15 * * MON-FRI
#myapp.squareoff-cron=0 55 15 * * *
myapp.squareoff-zone=Asia/Kolkata
myapp.exit-max-attempt=5
myapp.ticksize-to-reduce=0.05
myapp.wait-time-between-partial-exits=300

myapp.ordercontext-save-interval-ms:300000

myapp.historic-data-days=5

