spring.application.name=local_to_smartapi

broker.api.base-url=https://apiconnect.angelone.in
broker.api.timeout.connect=2000
broker.api.timeout.response=2000


angel.base-url=https://apiconnect.angelone.in
angel.private-key=5hva6iDv
angel.client-local-ip=192.168.1.10
angel.client-public-ip=123.145.22.11
angel.client-mac-address=AA-BB-CC-DD-EE-FF
angel.source-id=WEB
angel.user-type=USER
angel.totp-code=PF3ZHJPRNE7GDEVMRUIXQ6CFGE




